/w gm &{template:default}{{name=@{selected|name} - Moyenne}} {{Carac. = [[[[@{selected|modFORPJ}+@{selected|strength}+@{selected|modCONPJ}+@{selected|constitution}+@{selected|modDEXPJ}+@{selected|dexterity}+@{selected|modINTPJ}+@{selected|intelligence}+@{selected|modPOUPJ}+@{selected|power}+@{selected|modCARPJ}+@{selected|charisma}]]/6]]}}{{Comp. combat = [[[[@{selected|firearmsPJ}+@{selected|firearms}+@{selected|melee_weaponsPJ}+@{selected|melee_weapons}+@{selected|heavy_weaponsPJ}+@{selected|heavy_weapons}+@{selected|athleticsPJ}+@{selected|athletics}+@{selected|unarmed_combatPJ}+@{selected|unarmed_combat}+@{selected|stealthPJ}+@{selected|stealth}+@{selected|dodgePJ}+@{selected|dodge}+@{selected|alertnessPJ}+@{selected|alertness}]]/8]]}}{{Autre comp. = [[[[@{selected|bureaucracyPJ}+@{selected|bureaucracy}+@{selected|anthropologyPJ}+@{selected|anthropology}+@{selected|archeologyPJ}+@{selected|archeology}+@{selected|artPJ}+@{selected|art}+@{selected|artilleryPJ}+@{selected|artillery}+@{selected|craftPJ}+@{selected|craft}+@{selected|surgeryPJ}+@{selected|surgery}+@{selected|accountingPJ}+@{selected|accounting}+@{selected|drivePJ}+@{selected|drive}+@{selected|criminologyPJ}+@{selected|criminology}+@{selected|disguisePJ}+@{selected|disguise}+@{selected|demolitionsPJ}+@{selected|demolitions}+@{selected|ridePJ}+@{selected|ride}+@{selected|military_sciencePJ}+@{selected|military_science}+@{selected|historyPJ}+@{selected|history}+@{selected|HUMINTPJ}+@{selected|HUMINT}+@{selected|computer_sciencePJ}+@{selected|computer_science}+@{selected|lawPJ}+@{selected|law}+@{selected|heavy_machineryPJ}+@{selected|heavy_machinery}+@{selected|medicinePJ}+@{selected|medicine}+@{selected|forensicsPJ}+@{selected|forensics}+@{selected|swimPJ}+@{selected|swim}+@{selected|navigatePJ}+@{selected|navigate}+@{selected|occultPJ}+@{selected|occult}+@{selected|unnaturalPJ}+@{selected|unnatural}+@{selected|persuadePJ}+@{selected|persuade}+@{selected|pharmacyPJ}+@{selected|pharmacy}+@{selected|pilotPJ}+@{selected|pilot}+@{selected|first_aidPJ}+@{selected|first_aid}+@{selected|psychotherapyPJ}+@{selected|psychotherapy}+@{selected|searchPJ}+@{selected|search}+@{selected|sigintPJ}+@{selected|sigint}+@{selected|survivalPJ}+@{selected|survival}]]/33]]}}








